name: frontend_vesta
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^6.1.4
  firebase_core: ^4.1.0
  cloud_firestore: ^6.1.2
  fl_chart: ^1.1.1
  http: ^1.6.0
  intl: ^0.20.2
  async: ^2.13.0
  share_plus: ^12.0.1
  app_links: ^7.0.0
  freerasp: ^7.3.0
  flutter_secure_storage: ^10.0.0
  local_auth: ^3.0.0
  flutter_dotenv: ^5.1.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true


  assets:
    - .env
    - assets/images/vesta_logo.png
    - assets/images/LOGO_APP-ICON.png
    - assets/images/Dark.png
    - assets/images/choose_bank.png
    - assets/images/jopacc.png
    - assets/images/budgeting.png
    - assets/images/ahli.jpeg
    - assets/images/cboj.png
    - assets/images/etihad.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf