// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ09nLu5nkrIsNtOgz5h5InDkLoWbRIh8',
    appId: '1:579399466424:web:1522e96f9b536aa2cee34d',
    messagingSenderId: '579399466424',
    projectId: 'vesta-7e96a',
    authDomain: 'vesta-7e96a.firebaseapp.com',
    storageBucket: 'vesta-7e96a.firebasestorage.app',
    measurementId: 'G-ZRNTQVXCQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfPTW8al_dnzClUKa17rJ1QlsjunbQQNs',
    appId: '1:1089402463760:android:2c61b12e6fe0a9b7088c95',
    messagingSenderId: '1089402463760',
    projectId: 'vesta-83939',
    storageBucket: 'vesta-83939.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYxtZNuV_FSiyIGlklUX0ZPum0YVcQslM',
    appId: '1:579399466424:ios:53f9a564c22ef42fcee34d',
    messagingSenderId: '579399466424',
    projectId: 'vesta-7e96a',
    storageBucket: 'vesta-7e96a.firebasestorage.app',
    iosBundleId: 'com.example.frontendVesta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYxtZNuV_FSiyIGlklUX0ZPum0YVcQslM',
    appId: '1:579399466424:ios:53f9a564c22ef42fcee34d',
    messagingSenderId: '579399466424',
    projectId: 'vesta-7e96a',
    storageBucket: 'vesta-7e96a.firebasestorage.app',
    iosBundleId: 'com.example.frontendVesta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ09nLu5nkrIsNtOgz5h5InDkLoWbRIh8',
    appId: '1:579399466424:web:d38881940d175f58cee34d',
    messagingSenderId: '579399466424',
    projectId: 'vesta-7e96a',
    authDomain: 'vesta-7e96a.firebaseapp.com',
    storageBucket: 'vesta-7e96a.firebasestorage.app',
    measurementId: 'G-HFLRFYG9ND',
  );
}
